# install python from google 

# Go window powershell terminal for install the numpy library & jupyter notebook

# pip install numpy    for install the python library
# pip install jupyter noteboke    for install the jupyter notebook

# After install the python library and Junyper notebook go jupyter notebook and create the new Python file

# import numpy as np     for import the numpy library


# NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
# NumPy is a Python library used for working with arrays. At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed ...

In [1]:
 import numpy as np

In [2]:
ar = np.array([2,7,1,9,5])

In [3]:
ar

array([2, 7, 1, 9, 5])

In [4]:
print("Hello World")

Hello World


In [5]:
ar[0]

2

In [6]:
ar[3]

9

In [7]:
ar[1]+ar[2]

8

In [8]:
ar.dtype

dtype('int32')

In [9]:
myar = np.array([1,4,3,6,9], np.int8)

In [10]:
myar

array([1, 4, 3, 6, 9], dtype=int8)

In [11]:
ar1 = np.array([[12,33,42,56,63]])

In [12]:
ar1

array([[12, 33, 42, 56, 63]])

In [13]:
ar1[0,1]

33

In [14]:
ar1[0,3]

56

In [15]:
ar1.shape

(1, 5)

In [16]:
ar1.dtype

dtype('int32')

In [17]:
ar1[0,0] = 99 

In [18]:
ar1

array([[99, 33, 42, 56, 63]])

In [19]:
ar1.size

5

In [20]:
listar = np.array([[2,4,4],[6,7,3],[8,3,1]])

In [21]:
listar

array([[2, 4, 4],
       [6, 7, 3],
       [8, 3, 1]])

In [22]:
listar.dtype

dtype('int32')

In [23]:
listar.size

9

In [24]:
listar.shape

(3, 3)

In [25]:
listar[1,0] = 9 

In [26]:
listar

array([[2, 4, 4],
       [9, 7, 3],
       [8, 3, 1]])

In [27]:
listar.T

array([[2, 9, 8],
       [4, 7, 3],
       [4, 3, 1]])

In [28]:
listar

array([[2, 4, 4],
       [9, 7, 3],
       [8, 3, 1]])

In [29]:
np.array({23,44,67,35,68})

array({67, 35, 68, 23, 44}, dtype=object)

# Conversion from other Python structures (e.g., lists, tuples)
# Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)

In [30]:
arzero = np.zeros((2,5))

In [31]:
arzero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
arzero.dtype

dtype('float64')

In [33]:
arzero.size

10

In [34]:
arzero.shape

(2, 5)

In [35]:
arone = np.ones((2,5))

In [36]:
arone

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
arone

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
ar.shape

(5,)

In [39]:
ar.size

5

In [40]:
ar.dtype

dtype('int32')

In [41]:
rang = np.arange(9)

In [42]:
rang

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
rang.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
rang

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
r1 = rang.reshape(3,3)

In [46]:
r1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
r1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [48]:
rang1 = np.arange(5,10)

In [49]:
rang1

array([5, 6, 7, 8, 9])

In [50]:
rang2 = np.arange(1,10,3)

In [51]:
rang2

array([1, 4, 7])

In [52]:
rang2.dtype

dtype('int32')

In [53]:
rang2.size

3

In [54]:
rang2.shape

(3,)

In [55]:
lspace = np.linspace(1,5,12)

In [56]:
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [57]:
lspace1 = np.linspace(1,3,5)

In [58]:
lspace1

array([1. , 1.5, 2. , 2.5, 3. ])

In [59]:
lspace1.dtype

dtype('float64')

In [60]:
lspace1.size

5

In [61]:
lspace1.shape

(5,)

In [62]:
# empty give you a ramdom elements of array
emp = np.empty((2,5))

In [63]:
emp

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [64]:
emp_like = np.empty_like(emp)

In [65]:
emp_like

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
ide = np.identity(10)

In [67]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [68]:
ide.shape

(10, 10)

In [69]:
ide.size

100

In [70]:
ide.dtype

dtype('float64')

# 1D Array = [23,56,35,86,76]  Axis 0    Rows
# 2D Array = [[12,32,43],[55,67,24],[68,87,78]]   Axis 1    Columns

In [71]:
a = np.array([[2,3,5],[1,2,3],[3,5,3]])

In [72]:
a

array([[2, 3, 5],
       [1, 2, 3],
       [3, 5, 3]])

In [73]:
a.sum(axis = 0)

array([ 6, 10, 11])

In [74]:
a.sum(axis = 1)

array([10,  6, 11])

In [75]:
a.T

array([[2, 1, 3],
       [3, 2, 5],
       [5, 3, 3]])

In [76]:
# flat give you a iterate
a.flat

In [77]:
for i in a.flat:
    print(i)

2
3
5
1
2
3
3
5
3


In [78]:
# ndim you the dimension of the Array
a.ndim

2

In [79]:
a.size

9

In [80]:
a.dtype

dtype('int32')

In [81]:
a.shape

(3, 3)

In [82]:
a.nbytes

36

In [83]:
a1 = np.array([4,2,6,1,7])

In [84]:
a1

array([4, 2, 6, 1, 7])

In [85]:
# argmax give you the maximun element of index
a1.argmax()

4

In [86]:
a1.argmin()

3

In [87]:
a1.argsort()

array([3, 1, 0, 2, 4], dtype=int64)

In [88]:
a = np.array([[2,3,5],[1,2,3],[3,5,3]])

In [89]:
a

array([[2, 3, 5],
       [1, 2, 3],
       [3, 5, 3]])

In [90]:
a.argmax()

2

In [91]:
a.argmin()

3

In [92]:
a.argmax(axis = 0)

array([2, 2, 0], dtype=int64)

In [93]:
a.argmax(axis = 1)

array([2, 2, 1], dtype=int64)

In [94]:
a.argmax(axis = 1)

array([2, 2, 1], dtype=int64)

In [95]:
a.argmin(axis = 1)

array([0, 0, 0], dtype=int64)

In [96]:
a.argsort(axis = 0)

array([[1, 1, 1],
       [0, 0, 2],
       [2, 2, 0]], dtype=int64)

In [97]:
a.argsort(axis = 1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [98]:
a = np.array([[2,3,5],[1,2,3],[3,5,3]])

In [99]:
a

array([[2, 3, 5],
       [1, 2, 3],
       [3, 5, 3]])

In [100]:
aa = np.array([[2,1,3],[1,3,4],[2,4,1]])

In [101]:
aa

array([[2, 1, 3],
       [1, 3, 4],
       [2, 4, 1]])

In [102]:
a + aa

array([[4, 4, 8],
       [2, 5, 7],
       [5, 9, 4]])

In [103]:
[1,2,3] + [2,4,6]

[1, 2, 3, 2, 4, 6]

In [104]:
# sqrt you give the square root of the elements 
np.sqrt(aa)

array([[1.41421356, 1.        , 1.73205081],
       [1.        , 1.73205081, 2.        ],
       [1.41421356, 2.        , 1.        ]])

In [105]:
aa = np.array([[2,1,3],[1,3,4],[2,4,1]])

In [106]:
aa

array([[2, 1, 3],
       [1, 3, 4],
       [2, 4, 1]])

In [107]:
aa.sum()

21

In [108]:
aa.max()

4

In [109]:
aa.min()

1

In [110]:
np.where(aa>3)

(array([1, 2], dtype=int64), array([2, 1], dtype=int64))

In [111]:
np.where(aa<2)

(array([0, 1, 2], dtype=int64), array([1, 0, 2], dtype=int64))

In [112]:
# count_nonzero  give the nonzero elements
np.count_nonzero(aa)

9

In [113]:
np.nonzero(aa)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [114]:
aa.itemsize

4

In [115]:
aa.size

9

In [116]:
# find the size of Array
aa.itemsize * aa.size

36

# Thank You ! You Watched this Video at the END 

# Maybe This Video is Very Helpful for You

# Please Subscribe the Channel Comment & Like Also ! 

#                                                          Thank You All  !